<?php
/**
* @file
* A description of what your module does.
*/
function dracars_webform_email_webform_submission_render_alter(&$renderable) {
  /**
   * Add colon to %email_keys in webform emails
   */
  foreach (element_children($renderable) as $key) {
    $renderable[$key]['#title'] = '<br>' . '<strong>' . $renderable[$key]['#title'] . '</strong>' . ':';
    if (isset($renderable[$key]['#webform_component']['type']) && $renderable[$key]['#webform_component']['type'] == 'fieldset') {
      $fieldset = &$renderable[$key];
      foreach (element_children($fieldset) as $key2) {
        $fieldset[$key2]['#title'] = '<br>' . '<strong>' . $fieldset[$key2]['#title'] . '</strong>' . ':';
      }
    }
  }
}